package co.cobre.jbpm.core.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SaldoEmisorResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SaldoEmisorResponse() {
    }




}